/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcOatProductionCostInputs {
    'socket': string;
  }
  interface AgcOatProductionCostInputsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcOatProductionCostProgress {
    'socket': string;
  }
  interface AgcOatProductionCostProgressAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcOatProductionCostResultsPlaceholder {}
  interface AgcOatProductionCostResultsPlaceholderAttributes extends StencilHTMLAttributes {}

  interface AgcOatProductionCostResults {
    'socket': string;
  }
  interface AgcOatProductionCostResultsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcOatProductionCost {
    'mode': "full" | "step";
    'socket': string;
    'tract': string;
    'units': any;
  }
  interface AgcOatProductionCostAttributes extends StencilHTMLAttributes {
    'mode'?: "full" | "step";
    'onAgcCalculated'?: (event: CustomEvent) => void;
    'onAgcStepChanged'?: (event: CustomEvent) => void;
    'socket'?: string;
    'tract'?: string;
    'units'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgcOatProductionCostInputs': Components.AgcOatProductionCostInputs;
    'AgcOatProductionCostProgress': Components.AgcOatProductionCostProgress;
    'AgcOatProductionCostResultsPlaceholder': Components.AgcOatProductionCostResultsPlaceholder;
    'AgcOatProductionCostResults': Components.AgcOatProductionCostResults;
    'AgcOatProductionCost': Components.AgcOatProductionCost;
  }

  interface StencilIntrinsicElements {
    'agc-oat-production-cost-inputs': Components.AgcOatProductionCostInputsAttributes;
    'agc-oat-production-cost-progress': Components.AgcOatProductionCostProgressAttributes;
    'agc-oat-production-cost-results-placeholder': Components.AgcOatProductionCostResultsPlaceholderAttributes;
    'agc-oat-production-cost-results': Components.AgcOatProductionCostResultsAttributes;
    'agc-oat-production-cost': Components.AgcOatProductionCostAttributes;
  }


  interface HTMLAgcOatProductionCostInputsElement extends Components.AgcOatProductionCostInputs, HTMLStencilElement {}
  var HTMLAgcOatProductionCostInputsElement: {
    prototype: HTMLAgcOatProductionCostInputsElement;
    new (): HTMLAgcOatProductionCostInputsElement;
  };

  interface HTMLAgcOatProductionCostProgressElement extends Components.AgcOatProductionCostProgress, HTMLStencilElement {}
  var HTMLAgcOatProductionCostProgressElement: {
    prototype: HTMLAgcOatProductionCostProgressElement;
    new (): HTMLAgcOatProductionCostProgressElement;
  };

  interface HTMLAgcOatProductionCostResultsPlaceholderElement extends Components.AgcOatProductionCostResultsPlaceholder, HTMLStencilElement {}
  var HTMLAgcOatProductionCostResultsPlaceholderElement: {
    prototype: HTMLAgcOatProductionCostResultsPlaceholderElement;
    new (): HTMLAgcOatProductionCostResultsPlaceholderElement;
  };

  interface HTMLAgcOatProductionCostResultsElement extends Components.AgcOatProductionCostResults, HTMLStencilElement {}
  var HTMLAgcOatProductionCostResultsElement: {
    prototype: HTMLAgcOatProductionCostResultsElement;
    new (): HTMLAgcOatProductionCostResultsElement;
  };

  interface HTMLAgcOatProductionCostElement extends Components.AgcOatProductionCost, HTMLStencilElement {}
  var HTMLAgcOatProductionCostElement: {
    prototype: HTMLAgcOatProductionCostElement;
    new (): HTMLAgcOatProductionCostElement;
  };

  interface HTMLElementTagNameMap {
    'agc-oat-production-cost-inputs': HTMLAgcOatProductionCostInputsElement
    'agc-oat-production-cost-progress': HTMLAgcOatProductionCostProgressElement
    'agc-oat-production-cost-results-placeholder': HTMLAgcOatProductionCostResultsPlaceholderElement
    'agc-oat-production-cost-results': HTMLAgcOatProductionCostResultsElement
    'agc-oat-production-cost': HTMLAgcOatProductionCostElement
  }

  interface ElementTagNameMap {
    'agc-oat-production-cost-inputs': HTMLAgcOatProductionCostInputsElement;
    'agc-oat-production-cost-progress': HTMLAgcOatProductionCostProgressElement;
    'agc-oat-production-cost-results-placeholder': HTMLAgcOatProductionCostResultsPlaceholderElement;
    'agc-oat-production-cost-results': HTMLAgcOatProductionCostResultsElement;
    'agc-oat-production-cost': HTMLAgcOatProductionCostElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
